---

- name: Install RabbitMQ
  hosts: all
  become: yes

  vars:
    rabbitmq_daemon: rabbitmq-server
    rabbitmq_state: started
    rabbitmq_enabled: true
    rabbitmq_version: "3.7.26"

  roles:
    - geerlingguy.rabbitmq
